/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/

import FormalConjectures.Util.ProblemImports

/-!
# Erdős Problem 1134

Lower density of a set generated by linear operations.

DISPROVED

*Reference:* [erdosproblems.com/1134](https://www.erdosproblems.com/1134)
-/

open Finset

open scoped Topology Real

namespace Erdos1134

/-- Set closed under linear operations -/
def A : Set ℕ := sorry

/-- Lower density of set generated by linear operations -/
@[category research open, AMS 11]
theorem linear_operation_set_density (answer : Prop) :
    answer ↔ ∃ (c : ℝ), 0 < c ∧
      Filter.liminf (fun X => (A ∩ Set.Icc 1 X).ncard / X) Filter.atTop ≥ c := by
  sorry

end Erdos1134
